import { callOllama } from "@/lib/ollama";

const SYSTEM_PROMPT = `You are a Senior QA Reviewer. You review a complete web app (HTML + CSS + JS) against the original request.

Your job: decide if the output is ACCEPTABLE or needs REWORK.

Check these areas:
1. FUNCTIONALITY — Does the app do what was requested? Are buttons wired up? Do features work?
2. LAYOUT — Is the page layout sensible? Are elements properly spaced and aligned? Nothing overlapping or off-screen?
3. STYLING — Does the CSS look reasonable? Proper fonts, colors, spacing? Not broken or unstyled?
4. COMPLETENESS — Are all requested features present in the HTML/JS? Any placeholder stubs left?

Be pragmatic — this is generated by a small model. Don't demand perfection.
FAIL only for: broken layout, missing core features, completely unstyled output, non-functional JS.
PASS if: the app mostly works and looks reasonable even if not beautiful.

Reply in this EXACT format:
>>REVIEW
verdict: PASS or REWORK
issues:
- (one issue per line, or "none" if passing)
>>END

If verdict is REWORK, list the specific issues to fix (max 5). Each issue must name the file and what to fix.`;

export interface HolisticReviewResult {
  verdict: "PASS" | "REWORK";
  issues: string[];
  raw: string;
  prompt: string;
  tokens: number;
  durationMs: number;
}

export async function runHolisticReview(
  model: string,
  projectName: string,
  projectDescription: string,
  files: { path: string; content: string }[],
): Promise<HolisticReviewResult> {
  const fileList = files
    .map((f) => `--- ${f.path} ---\n${f.content}`)
    .join("\n\n");

  const userMessage = `Original request: "${projectName}: ${projectDescription}"

Complete project output:
${fileList}

Review this output against the original request:`;

  const { text, prompt, tokens, durationMs } = await callOllama(
    model,
    "reviewer",
    SYSTEM_PROMPT,
    userMessage,
    { numPredict: 600 },
  );

  // Parse the response
  const verdictMatch = text.match(/verdict:\s*(PASS|REWORK)/i);
  const verdict: "PASS" | "REWORK" =
    verdictMatch && verdictMatch[1].toUpperCase() === "REWORK"
      ? "REWORK"
      : "PASS";

  const issues: string[] = [];
  const issuesMatch = text.match(/issues:\s*\n([\s\S]*?)(?:>>END|$)/i);
  if (issuesMatch) {
    const lines = issuesMatch[1].split("\n");
    for (const line of lines) {
      const trimmed = line.replace(/^-\s*/, "").trim();
      if (trimmed && trimmed.toLowerCase() !== "none" && trimmed !== ">>END") {
        issues.push(trimmed);
      }
    }
  }

  return { verdict, issues, raw: text, prompt, tokens, durationMs };
}
